server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8

spring:
  jackson:
    serialization:
      INDENT_OUTPUT: true
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=true&autoReconnect=true
    username: root
    password: 123456
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
  devtools:
    remote:
      secret: this is a secret
  mvc:
    throw-exception-if-no-handler-found: true
logging:
  level:
    org.springframework:
      data: DEBUG
      security: DEBUG
jwt:
  header: Authorization
  secret: mySecret
  expiration: 604800
  tokenHead: "Bearer "
  route:
    authentication:
      path: auth
      refresh: refresh
      register: "auth/register"